// Bundle the demo client into one self-contained HTML file (dist/index.html), which the
// demo modules serve from their own HTTP route.
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = await build({
  entryPoints: [join(here, 'src/main.ts')],
  bundle: true,
  format: 'esm',
  target: 'es2022',
  minify: true,
  write: false,
  legalComments: 'none',
});
const js = out.outputFiles[0].text.replaceAll('</script', '<\\/script');
const html = readFileSync(join(here, 'index.html'), 'utf8').replace('/*BUNDLE*/', () => js);
mkdirSync(join(here, 'dist'), { recursive: true });
writeFileSync(join(here, 'dist/index.html'), html);
// The TypeScript demo module imports the page as a string.
writeFileSync(
  join(here, '../typescript/src/page.gen.ts'),
  `// Generated by demo/web/build.mjs. Do not edit.\nexport default ${JSON.stringify(html)};\n`
);
console.log(`dist/index.html: ${(html.length / 1024).toFixed(0)} KB`);
