// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import DemoMoveReducer from "../demo_move_reducer";
import DemoSetNameReducer from "../demo_set_name_reducer";
import VoipCreateRoomReducer from "../voip_create_room_reducer";
import VoipJoinReducer from "../voip_join_reducer";
import VoipLeaveReducer from "../voip_leave_reducer";
import VoipModerateReducer from "../voip_moderate_reducer";
import VoipSendReducer from "../voip_send_reducer";
import VoipSetDeafenedReducer from "../voip_set_deafened_reducer";
import VoipSetMutedReducer from "../voip_set_muted_reducer";

export type DemoMoveParams = __Infer<typeof DemoMoveReducer>;
export type DemoSetNameParams = __Infer<typeof DemoSetNameReducer>;
export type VoipCreateRoomParams = __Infer<typeof VoipCreateRoomReducer>;
export type VoipJoinParams = __Infer<typeof VoipJoinReducer>;
export type VoipLeaveParams = __Infer<typeof VoipLeaveReducer>;
export type VoipModerateParams = __Infer<typeof VoipModerateReducer>;
export type VoipSendParams = __Infer<typeof VoipSendReducer>;
export type VoipSetDeafenedParams = __Infer<typeof VoipSetDeafenedReducer>;
export type VoipSetMutedParams = __Infer<typeof VoipSetMutedReducer>;

