// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.11.0 (commit 6b6e0ab19e4f8f52472aa4379552e9593c8f53bb).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import DemoMoveReducer from "./demo_move_reducer";
import DemoSetNameReducer from "./demo_set_name_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import DemoPlayerRow from "./demo_player_table";

// Import namespace table schema definitions
import Voip_ListenRow from "./voip/listen_table";
import Voip_PeerRow from "./voip/peer_table";
import Voip_RoomRow from "./voip/room_table";
import Voip_PacketRow from "./voip/packet_table";

// Import namespace reducer arg schemas
import Voip_CreateRoomReducer from "./voip/create_room_reducer";
import Voip_JoinReducer from "./voip/join_reducer";
import Voip_LeaveReducer from "./voip/leave_reducer";
import Voip_ModerateReducer from "./voip/moderate_reducer";
import Voip_SendReducer from "./voip/send_reducer";
import Voip_SetDeafenedReducer from "./voip/set_deafened_reducer";
import Voip_SetMutedReducer from "./voip/set_muted_reducer";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  demoPlayer: __table({
    name: 'demo_player',
    indexes: [
      { accessor: 'identity', name: 'demo_player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'demo_player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, DemoPlayerRow),
  "voip.listen": __table({
    name: 'voip.listen',
    indexes: [
      { accessor: 'audience', name: 'listen_audience_idx_btree', algorithm: 'btree', columns: [
        'audience',
      ] },
      { accessor: 'id', name: 'listen_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'listener', name: 'listen_listener_idx_btree', algorithm: 'btree', columns: [
        'listener',
      ] },
    ],
    constraints: [
      { name: 'listen_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, Voip_ListenRow),
  "voip.peer": __table({
    name: 'voip.peer',
    indexes: [
      { accessor: 'id', name: 'peer_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'peer_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'roomId', name: 'peer_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'peer_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'peer_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, Voip_PeerRow),
  "voip.room": __table({
    name: 'voip.room',
    indexes: [
      { accessor: 'id', name: 'room_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'room_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'room_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'room_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, Voip_RoomRow),
  "voip.packet": __table({
    name: 'voip.packet',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, Voip_PacketRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("demo_move", DemoMoveReducer),
  __reducerSchema("demo_set_name", DemoSetNameReducer),
  __reducerSchema("voip.create_room", Voip_CreateRoomReducer, "voip.createRoom"),
  __reducerSchema("voip.join", Voip_JoinReducer, "voip.join"),
  __reducerSchema("voip.leave", Voip_LeaveReducer, "voip.leave"),
  __reducerSchema("voip.moderate", Voip_ModerateReducer, "voip.moderate"),
  __reducerSchema("voip.send", Voip_SendReducer, "voip.send"),
  __reducerSchema("voip.set_deafened", Voip_SetDeafenedReducer, "voip.setDeafened"),
  __reducerSchema("voip.set_muted", Voip_SetMutedReducer, "voip.setMuted"),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.11.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const __qb = __makeQueryBuilder(tablesSchema.schemaType);
export const tables = {
  demoPlayer: __qb.demoPlayer,
  voip: {
    listen: __qb["voip.listen"],
    peer: __qb["voip.peer"],
    room: __qb["voip.room"],
    packet: __qb["voip.packet"],
  },
} as const;

/** The reducers available in this remote SpacetimeDB module. */
const __reducerAccessors = __convertToAccessorMap(reducersSchema.reducersType.reducers);
export const reducers = {
  demoMove: __reducerAccessors.demoMove,
  demoSetName: __reducerAccessors.demoSetName,
  voip: {
    createRoom: __reducerAccessors["voip.createRoom"],
    join: __reducerAccessors["voip.join"],
    leave: __reducerAccessors["voip.leave"],
    moderate: __reducerAccessors["voip.moderate"],
    send: __reducerAccessors["voip.send"],
    setDeafened: __reducerAccessors["voip.setDeafened"],
    setMuted: __reducerAccessors["voip.setMuted"],
  },
} as const;

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

