// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const DemoPlayer = __t.object("DemoPlayer", {
  identity: __t.identity(),
  name: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
});
export type DemoPlayer = __Infer<typeof DemoPlayer>;

