// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  id: __t.u32(),
  roomId: __t.u64().name("room_id"),
  online: __t.bool(),
  muted: __t.bool(),
  deafened: __t.bool(),
  serverMuted: __t.bool().name("server_muted"),
  joinedAt: __t.timestamp().name("joined_at"),
});
