// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Cell = __t.object("Cell", {
  id: __t.u64(),
  roomId: __t.u64(),
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
});
export type Cell = __Infer<typeof Cell>;

export const Config = __t.object("Config", {
  key: __t.u8(),
  get settings() {
    return VoipSettings;
  },
});
export type Config = __Infer<typeof Config>;

export const Listen = __t.object("Listen", {
  id: __t.u64(),
  listener: __t.identity(),
  audience: __t.u64(),
});
export type Listen = __Infer<typeof Listen>;

export const Packet = __t.object("Packet", {
  audience: __t.u64(),
  speaker: __t.u32(),
  seq: __t.u32(),
  flags: __t.u8(),
  get pos() {
    return __t.option(VoipVec3);
  },
  data: __t.byteArray(),
});
export type Packet = __Infer<typeof Packet>;

export const Peer = __t.object("Peer", {
  identity: __t.identity(),
  id: __t.u32(),
  roomId: __t.u64(),
  online: __t.bool(),
  muted: __t.bool(),
  deafened: __t.bool(),
  serverMuted: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type Peer = __Infer<typeof Peer>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  name: __t.string(),
  spatial: __t.bool(),
  range: __t.f32(),
  locked: __t.bool(),
  maxPeers: __t.u32(),
  owner: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const Speaker = __t.object("Speaker", {
  identity: __t.identity(),
  peerId: __t.u32(),
  audience: __t.u64(),
  canSpeak: __t.bool(),
  spatial: __t.bool(),
  get pos() {
    return __t.option(VoipVec3);
  },
  get cell() {
    return __t.option(VoipCellCoord);
  },
  tokens: __t.f64(),
  refilledAt: __t.timestamp(),
});
export type Speaker = __Infer<typeof Speaker>;

export const VoipCellCoord = __t.object("VoipCellCoord", {
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
});
export type VoipCellCoord = __Infer<typeof VoipCellCoord>;

export const VoipSettings = __t.object("VoipSettings", {
  maxPacketBytes: __t.u32(),
  rateBytesPerSec: __t.u32(),
  burstBytes: __t.u32(),
  packetOverhead: __t.u32(),
  clientsCreateRooms: __t.bool(),
});
export type VoipSettings = __Infer<typeof VoipSettings>;

export const VoipVec3 = __t.object("VoipVec3", {
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
});
export type VoipVec3 = __Infer<typeof VoipVec3>;

