// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import DemoMoveReducer from "../demo_move_reducer";
import DemoSetNameReducer from "../demo_set_name_reducer";

export type DemoMoveParams = __Infer<typeof DemoMoveReducer>;
export type DemoSetNameParams = __Infer<typeof DemoSetNameReducer>;

