// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const DemoPlayer = __t.object("DemoPlayer", {
  identity: __t.identity(),
  name: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
});
export type DemoPlayer = __Infer<typeof DemoPlayer>;

export const VoipCell = __t.object("VoipCell", {
  id: __t.u64(),
  roomId: __t.u64(),
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
});
export type VoipCell = __Infer<typeof VoipCell>;

export const VoipCellCoord = __t.object("VoipCellCoord", {
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
});
export type VoipCellCoord = __Infer<typeof VoipCellCoord>;

export const VoipConfig = __t.object("VoipConfig", {
  key: __t.u8(),
  get settings() {
    return VoipSettings;
  },
});
export type VoipConfig = __Infer<typeof VoipConfig>;

export const VoipListen = __t.object("VoipListen", {
  id: __t.u64(),
  listener: __t.identity(),
  audience: __t.u64(),
});
export type VoipListen = __Infer<typeof VoipListen>;

export const VoipPacket = __t.object("VoipPacket", {
  audience: __t.u64(),
  speaker: __t.u32(),
  seq: __t.u32(),
  flags: __t.u8(),
  get pos() {
    return __t.option(VoipVec3);
  },
  data: __t.byteArray(),
});
export type VoipPacket = __Infer<typeof VoipPacket>;

export const VoipPeer = __t.object("VoipPeer", {
  identity: __t.identity(),
  id: __t.u32(),
  roomId: __t.u64(),
  online: __t.bool(),
  muted: __t.bool(),
  deafened: __t.bool(),
  serverMuted: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type VoipPeer = __Infer<typeof VoipPeer>;

export const VoipRoom = __t.object("VoipRoom", {
  id: __t.u64(),
  name: __t.string(),
  spatial: __t.bool(),
  range: __t.f32(),
  locked: __t.bool(),
  maxPeers: __t.u32(),
  owner: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
});
export type VoipRoom = __Infer<typeof VoipRoom>;

export const VoipSettings = __t.object("VoipSettings", {
  maxPacketBytes: __t.u32(),
  rateBytesPerSec: __t.u32(),
  burstBytes: __t.u32(),
  packetOverhead: __t.u32(),
  clientsCreateRooms: __t.bool(),
});
export type VoipSettings = __Infer<typeof VoipSettings>;

export const VoipSpeaker = __t.object("VoipSpeaker", {
  identity: __t.identity(),
  peerId: __t.u32(),
  audience: __t.u64(),
  canSpeak: __t.bool(),
  spatial: __t.bool(),
  get pos() {
    return __t.option(VoipVec3);
  },
  get cell() {
    return __t.option(VoipCellCoord);
  },
  tokens: __t.f64(),
  refilledAt: __t.timestamp(),
});
export type VoipSpeaker = __Infer<typeof VoipSpeaker>;

export const VoipVec3 = __t.object("VoipVec3", {
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
});
export type VoipVec3 = __Infer<typeof VoipVec3>;

