// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  VoipVec3,
} from "./types";


export default __t.row({
  audience: __t.u64(),
  speaker: __t.u32(),
  seq: __t.u32(),
  flags: __t.u8(),
  get pos() {
    return __t.option(VoipVec3);
  },
  data: __t.byteArray(),
});
